name=CU205SCPB
version=1.3.2
author=Marco Henrique Luiz Alexandrino
maintainer=Marco Henrique Luiz Alexandrino
sentence=Arduino library for Noritake CU205SCPB-T21A VFD displays.
paragraph=Library for controlling Noritake CU205SCPB-T21A VFD displays through the 8-bit parallel interface, including cursor control, text effects, scrolling, brightness adjustment and progress bar.
category=Display
url=https://github.com/marcohpa-star/CU205SCPB-Arduino
architectures=*
