name=CU205SCPB
version=1.1.0
author=Marco Henrique
maintainer=Marco Henrique
sentence=Arduino library for Noritake CU205SCPB-T21A VFD display
paragraph=8-bit parallel driver for Noritake CU205SCPB-T21A VFD modules using Epson SED2000F controller.
category=Display
url=https://github.com/marcohpa-star/CU205SCPB-Arduino
architectures=*
